---
- hosts: localhost
  tasks:
    - name: Construindo a imagem Docker do Bookstack
      command: docker image build -t bookstack .
      args:
        chdir: /root/dockerfile-bookstack

    - name: Etiquetando a imagem Docker do Bookstack
      command: docker tag bookstack:latest <seu-usuario-docker>/bookstack:latest

    - name: Enviando imagem Docker do Bookstack para DockerHub
      command: docker image push <seu-usuario-docker>/bookstack:latest

    - name: Removendo a imagem Docker (local) do Bookstack
      command: docker image rmi <seu-usuario-docker>/bookstack:latest

    - name: Construindo a imagem Docker do MariaDB
      command: docker image build -t mariadb .
      args:
        chdir: /root/dockerfile-mariadb

    - name: Etiquetando a imagem Docker do MariaDB
      command: docker tag mariadb:latest <seu-usuario-docker>/mariadb:latest

    - name: Enviando a imagem Docker do MariaDB para DockerHub
      command: docker image push <seu-usuario-docker>/mariadb

    - name: Removendo a imagem Docker (local) do MariaDB
      command: docker image rmi <seu-usuario-docker>/mariadb

- hosts: webapp-node
  tasks:
    - name: Executando o docker-compose
      command: docker-compose -f /root/docker-compose.yml up -d
#    - name: Parando o container
#      command:  docker container stop bookstack
#    - name: Removendo o container
#      command: docker container rm bookstack
#    - name: Removendo a imagem docker
#      command: docker image rm <seu-usuario-docker>/bookstack
#    - name: Criando um container novo
#      command: docker container run -itd --name devopscontainer -p 9000:80 <seu-usuario-docker>/bookstack
