- hosts: all
  tasks:             
    - name: stop container
      shell:  docker container stop devopscontainer                    
    - name: remove container
      shell: docker container rm devopscontainer
    - name: remove docker image
      shell: docker image rm eduvasconcelos/devops_ci_cd_jenkins            
    - name: create new container
      shell: docker container run -itd --name devopscontainer -p 9000:80 eduvasconcelos/devops_ci_cd_jenkins
