site_name: Projeto de Devops e CI/CD - Realizando o deploy de aplicações web
site_url: https://EduardoVasconceloss.github.io/devops-ci-cd-project/
site_author: Eduardo Vasconcelos
site_description: >-
  Projeto de DevOps e integração contínua/entrega contínua (CI/CD) utilizando Jenkins, Ansible, e Docker para o deploy automatizado de aplicações, incluindo Bookstack e Mariadb.
repo_name: EduardoVasconceloss/devops-ci-cd-project
repo_url: https://github.com/EduardoVasconceloss/devops-ci-cd-project
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/EduardoVasconceloss"  target="_blank" rel="noopener">Eduardo Vasconcelos</a>
